<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_tutorial_gazebo">
  <gazebo>
   <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
     <alwaysOn>false</alwaysOn>
     <legacyMode>false</legacyMode>
     <updateRate>20</updateRate>
     <leftJoint>left_wheel_joint</leftJoint>
     <rightJoint>right_wheel_joint</rightJoint>
     <wheelSeparation>${wheel_separation}</wheelSeparation>
     <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
     <torque>20</torque>
     <commandTopic>/cmd_vel</commandTopic>
     <odometryTopic>/odom</odometryTopic>
     <odometryFrame>odom</odometryFrame>
     <robotBaseFrame>base_footprint</robotBaseFrame>
   </plugin>
 </gazebo>

 <xacro:macro name="gazebo_laser_link" params="location">
   <gazebo reference="laser_link_${location}">
     <sensor type="ray" name="laser_sensor_${location}">
       <pose>0 0 0 0 0 0</pose>
       <visualize>true</visualize>
       <update_rate>40</update_rate>
       <ray>
         <scan>
           <horizontal>
             <samples>5</samples>
             <min_angle>-0.0349066</min_angle>
             <max_angle>0.0349066</max_angle>
           </horizontal>
         </scan>
         <range>
           <min>0.10</min>
           <max>30.0</max>
           <resolution>0.01</resolution>
         </range>
         <noise>
           <type>gaussian</type>
           <mean>0.0</mean>
           <stddev>0.01</stddev>
         </noise>
       </ray>
       <plugin name="gazebo_ros_head_hokuyo_controller_${location}" filename="libgazebo_ros_laser.so">
         <topicName>/scan_${location}</topicName>
         <frameName>laser_link_${location}</frameName>
       </plugin>
     </sensor>
     <material>Gazebo/Green</material>
   </gazebo>
 </xacro:macro>
  
 <xacro:gazebo_laser_link location="right"/>
 <xacro:gazebo_laser_link location="center"/>
 <xacro:gazebo_laser_link location="left"/>

 <gazebo reference="base_link">
   <material>Gazebo/White</material>
 </gazebo>
 <gazebo reference="left_wheel">
   <material>Gazebo/Red</material>
 </gazebo>
 <gazebo reference="right_wheel">
   <material>Gazebo/Red</material>
 </gazebo>
</robot>
